### ISSUE TITLE
Your Experience at HM and How Is HumanMade Different From Other WP Companies?

### ISSUE THREAD

**Issue by ahmadawais** [rmccue/ama#10]
More importantly, I find it fascinating that HM allows its employees to invest so much time for the benefit of all instead of some i.e. contributing to the WP Core with tools which no one else would touch. 

That's not to say, that your efforts don't count. But I guess two hands are needed if you want to clap. Would like to know more about that :)

**Comment by rmccue** [comment]
I think there are a lot of companies in the WP space that do this, even more so than HM. Generally speaking though, we work a little differently to some others; everyone is encouraged to contribute a bit, rather than a few people contributing a lot. It just so happens that a lot of the stuff I work on happens to be pretty visible; we have lots of other open source projects that are just as important, yet aren't seen as much.

This contribution isn't purely out of the goodness of our hearts (although we're pretty nice people), it also benefits us. Often bugs that are fixed in WP are things we've run into that we want to fix for ourselves, and that happen to benefit everyone else too. Other projects are the same: CMB, Mercator, S3 Uploads, etc are all things that we need that happen to be beneficial to everyone else too.

As an example, the Importer rewrite is something that came out of a client project I was working on. I was working on importing the client's data locally, and noticed that importing a 40MB XML file required many times the amount of memory (130MB). This annoyed me, and I happen to have the right intersection of knowledge to fix that problem. This benefits us internally by improving a process that we have to use a lot for client sites, and there's no reason to not share that with everyone else too.

With all that said, @willmot might have a different answer to this question, and he's the one who runs the company. :)

**Comment by ahmadawais** [comment]
Anyways, I think it is great to be working for a company where the client needs kind of intersect with the needs of masses and all. I appreciate all that you guys have been doing for WP irrespective of the reasons behind doing it.
