### ISSUE TITLE
What do you spend most of your work-time doing?

### ISSUE THREAD

**Issue by JJJ** [rmccue/ama#13]
Externally, it looks like you spend a lot of time working on core and REST, but we both know that doesn't help HumanMade make payroll. It's important to give back, but it's unrealistic to expect to go broke supporting your own open-source endeavors.

What other non-core/REST work stuff are you doing these days?

**Comment by rmccue** [comment]
Since I joined Human Made through to October this year, I was full-time on product development. This was primarily working on [Happytables](http://happytables.com/) through all its iterations (the original website builder, the rebuild with frontend editing, and the pivot to the in-restaurant dashboard). The actual amount of "full-time" work varied, from 5 days a week to 3 days + 2 days on open source, to 2/2/1 (HT, other products, and open source). As it turned out, splitting my time so much was exhausting, so I settled back on full-time on HT. This also eventually changed to a combination of project management and development.

However, since October, I changed roles (I'm now Engineering Director), and I'm now working on all sorts of different stuff. My new role includes a lot of work on common tooling and processes used by everyone else, and open source naturally flows on to that. (One of my main projects right now is improving [Chassis](https://github.com/Chassis/Chassis), and working on a GUI for it.)

Typically, I don't do client work (since until recently I've been product-focussed), but it does come up occasionally. Often, that comes in the form of API-related consultation on projects.

---

It's important to also note that HM does plenty of stuff that isn't directly profitable, either to give back to the community, or to derive indirect benefits from it. The work we put in to the REST API comes back to us through community recognition and better standing in the community, as well as generating new project opportunities with API-driven clients. A *lot* of our clients have things which involve the REST API in some way, from frontend editors and page builders to entirely headless sites. I've no idea if that pays for itself (I doubt it does), but it does have tangible benefits.

Even if it didn't, I (mostly) enjoy working on it, so I'd likely still have work time for it anyway. Most people who want to work on open source projects have some sort of work time allocated for it, just because giving back is mostly just a good thing to do.
