### ISSUE TITLE
What is your suggestion for people who want to get involved in Open Source projects but don't know where to start?

### ISSUE THREAD

**Issue by nickperkins** [rmccue/ama#14]

**Comment by rmccue** [comment]
Despite what people claim, getting involved in open source is hard. Working with projects requires knowledge of the processes around the project, not just the codebase. GitHub improves this process for a lot of projects, but there's plenty of projects that aren't here, and not every project has contribution documentation.

The key steps I'd take are:
1. Pick a project you're interested in.
2. Work out how contribution works. Is there an issue tracker? Do they accept PRs? Who makes the decision to accept things?
3. Work out how the code works. Start writing code _after_ you work out the process.
4. Contribute that code. This could be a pull request, or it could be a patch file, depending on the project.

Lots of projects also have Good First Bug labels that allow newcomers to join in a lot easier, since they're minimal code, which allows you to focus on learning the process.

The best projects to get involved with (IMO) are mid-sized projects: a handful of regular contributors, but not so large to have a huge bureaucracy for contributing. WordPress plugins are a great example of this, especially when they're hosted on GitHub, as they're usually smaller codebases without too many snowflake processes.
