### ISSUE TITLE
What are the “serious problems with WordPress (mostly non-technical)” that you talk about in a prior answer?

### ISSUE THREAD

**Issue by alvarogois** [rmccue/ama#19]

**Comment by rmccue** [comment]
(Ref: https://github.com/rmccue/ama/issues/8#issuecomment-211160931)

There's various issues with WordPress' organisation and structure that make working *on* it a pain. Those issues are mostly not things I want to share publicly, because they're best discussed with people who can fix them rather than in public. That said, they also don't affect most people, who are merely working *with* WordPress instead. :)

**Comment by alvarogois** [comment]
Thank you @rmccue. Not that different from my own opinion. I don't have deep knowledge of it as you do, but I've been around for a while and see what it does to people. I'm inclined to believe WordPress as a serious problem of governance and transparency.
