### ISSUE TITLE
How do you take your coffee?

### ISSUE THREAD

**Issue by Japh** [rmccue/ama#3]
The next time we're in the same place at the same time, and there's a decent coffee machine available, if I were to make you the perfect coffee... what would you ask me to make? (Let's assume, for the moment, that I'm a coffee wizard and could make any sort of coffee you could dream up.) :coffee:

**Comment by rmccue** [comment]
My coffee choice generally fits into one of three baskets:
1. **Everyday coffee** - My standard workhorse coffee is the flat white. Smooth texture, but generally uninteresting. Works well as a "background" kind of coffee and doesn't distract. One sugar, mostly just to remove the "bite" of a strong coffee.
2. **Relaxation coffee** - If I feel like chilling out (mostly on the weekend), then a cappucino is the way to go. More interesting texture than a flat white, but not too out-there. Also lighter than a FW, since I'm usually taking my time to drink it. Usually no sugar, but may change.
3. **Coffee-as-an-Experience** - If I'm drinking coffee because I want to drink a coffee, all bets are out. Mocha, mochachino, espresso/doppio, café bombon, ristretto, and ice coffee have all been known to feature here. This is when I want something interesting for the sake of it, or want to enjoy the beans, or what-have-you.

**Comment by Japh** [comment]
Solid answer! We have good cross-over on #3  :smile:

**Comment by rmccue** [comment]
> there's a decent coffee machine available

p.s. we have one of these in the HM Brisbane office ;)

**Comment by Japh** [comment]
Next visit, let's play with coffee!!  :smile: :coffee:
