### ISSUE TITLE
What are your best travel tips?

### ISSUE THREAD

**Issue by Japh** [rmccue/ama#4]
You're a relatively frequent traveller, off to WordCamps and other events, both intra- and inter- nationally. What are your best tips for how to survive short- and long- haul flights in order to be productive while you're on the ground?

**Comment by rmccue** [comment]
Travel sucks no matter what you do.

The main problem for me (and I suspect you as well) is timezone shifts. Shifting my sleep cycle beforehand helps, but isn't a panacea. On the long flights (Trans-Pacific and Trans-Indian Ocean), I force myself to stay awake or sleep as appropriate for the timezone I'm travelling to, but not to the point of exhaustion, because you'll never be able to sleep particularly well on a flight.

It also helps that just generally, I don't get jetlag, so I adjust almost immediately. Typically, I'll avoid doing anything on the day I arrive, and get to bed at an appropriate time. The next day, I'm usually fully adjusted. I don't know if there's any real tips there, but it may help that I don't generally have a constant sleep schedule; I go to bed anywhere from 23:00 through 02:00 every night, so my body is on a reasonably flexible cycle anyway. (Whether that affects me regularly is another question.)

Lounge access helps for stopovers on long flights (i.e. BNE-DXB is 14 hours, then DXB to western Europe is another 7), but it isn't *that* great.

The only real thing really is to avoid travel in the first place. I try and group things together where possible, and aim to only travel to Europe/America 2-3 times a year. (This year is looking like twice to Europe, once to the US.) Fewer, longer sectors always beats out many short sectors though, looking forward to the PER-LHR direct flights next year.
