### ISSUE TITLE
Why the hell do you even use WordPress? 

### ISSUE THREAD

**Issue by aaronjorbin** [rmccue/ama#8]

**Comment by rmccue** [comment]
To be honestly, mostly inertia. WordPress does what I want some of the time, and I'm pretty lazy, so switching to a different CMS would require a lot of work.

Because of the inertia, I also know WP pretty well, so I know most stuff that's wrong with it. I'm an optimist, so I figure I can contribute to fixing a lot of the terribleness and help everyone out. I'm a fan of trying to make sure things are as good as possible for everyone else, even at my expense. :wink:

That said, there are serious problems with WordPress (mostly non-technical) that make me reconsider it constantly. I don't think these problems are unsolvable, but they're problematic to try and work with, and are extremely demoralising to try and work with.

Right now, I think the amount of good I can do outweighs the pain of dealing with these structural issues, and I'm happy to be the one to deal with that if everyone else can benefit from it. If that situation changed, I probably wouldn't use WordPress.
